version: "3.9"

services:
  api:
    ports:
      - "3001:3001"
    depends_on:
      database:
        condition: service_healthy
  database:
    ports:
      - "5432:5432"
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - db
    environment:
      POSTGRES_USER: kuma_admin
      POSTGRES_PASSWORD: Password1234
      POSTGRES_DB: kuma
    volumes:
      - db-data:/var/lib/postgresql/data
