server:
  port: 3001
spring:
  application:
    name: kuma-backend

  datasource:
    url: ${DB_URI:jdbc:postgresql://localhost:5432/kuma}
    password: ${DB_PASSWORD:Password1234}
    username: ${DB_USERNAME:kuma_admin}
    hikari:
      schema: kuma

  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    validate-migration-naming: true
    schemas: kuma
security:
  jwt:
    expiration-time: 86400000
    secret-key: ${JWT_SECRET:tiL5CUsiNAa1qkRZ4pt1x5f8gnp3aAp0tiL5CUsiNAa1qkRZ4pt1x5f8gnp3aAp0}
