ALTER TABLE kuma.term
    DROP CONSTRAINT term_pkey CASCADE;

ALTER TABLE kuma.term
    ADD COLUMN new_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE kuma.term
    rename column id to new_id_2;

ALTER TABLE kuma.term
    rename column new_id to id;

ALTER TABLE kuma.term
    ADD PRIMARY KEY (id);

